version: "3.9"

services:
  web:
    container_name: foodate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/www/foodate.ru/static:/code/www/static
      - /home/vasil1y/apps/foodate/uploads:/code/www/uploads
    depends_on:
      - db

  db:
    container_name: dev.db
    image: nouchka/sqlite3:latest
    volumes:
      - /home/vasil1y/apps/dev.foodate/db.sqlite3:/code/db.sqlite3
    environment:
      - SQLITE3_DB=/code/db.sqlite3
