name: Docker Image CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run Django tests
      run: |
        python3 set_example_env.py
        pip install -r requirements.txt
        python3 manage.py test

  build:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u gitlab-ci-token -p ${{ secrets.GITLAB_TOKEN }} ${{ secrets.GITLAB_URL }}
        docker build . --file Dockerfile --tag ${{ secrets.GITLAB_IMAGE }}:${{ github.ref_name }}
        docker push ${{ secrets.GITLAB_IMAGE }}:${{ github.ref_name }}

  deploy:
    needs: [test, build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to permkrovlya.ru
      run: |
        docker login -u gitlab-ci-token -p ${{ secrets.GITLAB_TOKEN }} ${{ secrets.GITLAB_URL }}
        docker pull ${{ secrets.GITLAB_IMAGE }}:${{ github.ref_name }}
        docker rm -f foodate || true
        docker run -d -p 445:445 --name foodate --env DEBUG=False --env SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' ${{ secrets.GITLAB_IMAGE }}:${{ github.ref_name }}
